services:
  web:
    container_name: web
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_PUBLISHABLE_KEY: ${SUPABASE_PUBLISHABLE_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      DASHBOARD_PASSCODE: ${DASHBOARD_PASSCODE}
      INGEST_BASIC_AUTH_USER: ${INGEST_BASIC_AUTH_USER}
      INGEST_BASIC_AUTH_PASS: ${INGEST_BASIC_AUTH_PASS}
